### ISSUE TITLE
Typo in fastcc.py

### ISSUE THREAD

**Issue by jyothischandran** [mpeel/fastcc#1]
I just noticed a typo in the line 368 of fastcc.py. (`cc = mbbb_v1.get(freq, 0)` ) There is an extra 'b' there.

**Comment by mpeel** [comment]
Good spot, thanks! Fixed with https://github.com/mpeel/fastcc/commit/b83d18c74d63bfef1bd1df86b467db1cda8ca0a9 and https://github.com/mpeel/fastcc/commit/91874d5004b5578b7f9c03e058dfb2fe36c47309 .

I don't think it would have affected any results, since this is a recent addition, and it would have thrown an error message.

**Comment by jyothischandran** [comment]
I understand . I just posted for the sake of completion! :)

**Comment by mpeel** [comment]
Many thanks for doing so! :-)
